[package]
name = "proc_macros"
version = "0.1.0"
authors = ["Antoine Murat <antoine.murat@protonmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0.18"